## Keep as back reference
spring:
  profiles:
    active: dev
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://47.98.180.157:3306/skylinehitech_sp?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: select 1

  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/agilent/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# jwt key config
jwt:
  tokenHeader: Authorization #JWT Request Header
  secret: mySecret
  expiration: 604800 # JWT out of date limit
  tokenHead: Bearer  # token of JWT

server:
  port: 8082
