spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cdsa?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: select 1
  jpa:
    database: mysql
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      databasePlatform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false

  thymeleaf:
    cache: false

logging:
  level:
    root: info
  path: ./logs
  config: classpath:./logback.xml

server:
  port: 8082

# 自定义接口配置
cdsa:
  interface-url: http://localhost:9190/api/CDSADa/InstrumentState

# 数据收集间隔
time:
  cron: 0/30 * *  * * ?