spring:
  profiles:
    include:
      - xiaomi-info
      - params
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cdsa?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: select 1
  jpa:
    database: mysql
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      databasePlatform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false

  thymeleaf:
    cache: false

server:
  port: 18080

logging:
  level:
    root: info
  path: ./logs
  config: classpath:./logback.xml

swagger:
  base-package: 'com.agilent.cdsa.controller'
  base-path: '/**'
  title: '注解方式的Swagger'
  description: '这是注解方式的Swagger'
  version: '1.0'
  license-url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  license: 'The Apache License'
  contact:
    name: 'AGILENT'
    url: 'https:www.agilent.com'

#License相关配置
license:
  subject: cdsa #主体 - 注意主体要与生成证书的主体一致一致，不然验证通过不了
  publicAlias: cdsa_publicCert #公钥别称
  storePass: agilent@123 #访问公钥的密码
  licensePath: license/cdsa_license.lic #license文件名，前缀为 classPath:resource目录
  publicKeysStorePath: license/cdsa_publicCerts.keystore #公钥位置

# REST Template
restTemplate:
  connectionRequestTimeout: 300000
  connectionTimeout: 300000
  readTimeout: 300000