## Keep as back reference
#  spring.datasource.url=jdbc:mariadb://47.98.180.157:3306/skylinehitech_sp
#  spring.datasource.username=root
#  spring.datasource.password=123456
#  spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#  spring.jpa.properties.hibernate.hbm2ddl.auto=update
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#  spring.jpa.show-sql=true

spring:
  profiles:
    active: dev
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cdsa?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: select 1
  jpa:
    database: mysql
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      databasePlatform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# jwt key config
jwt:
  tokenHeader: Authorization #JWT Request Header
  secret: mySecret
  expiration: 604800 # JWT out of date limit
  tokenHead: Bearer  # token of JWT

server:
  port: 8082
