spring:
  profiles:
    include:
      - xiaomi-info
      - params
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cdsa?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '123456'
    druid:
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: select 1
  jpa:
    database: mysql
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      databasePlatform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 18080

logging:
  level:
    root: info
  path: ./logs
  config: classpath:./logback.xml

#License相关配置
license:
  subject: iad #主体 - 注意主体要与生成证书的主体一致一致，不然验证通过不了
  publicAlias: iad_publicCert #公钥别称
  storePass: agilent@123 #访问公钥的密码
  licensePath: license/iad_license.lic #license文件名，前缀为 classPath:resource目录
  publicKeysStorePath: license/iad_publicCerts.keystore #公钥位置

# REST Template
restTemplate:
  connectionRequestTimeout: 300000
  connectionTimeout: 300000
  readTimeout: 300000

# SNMP Info
snmpInfo:
  communityName: public
  hostIp: 192.168.121.173
  port: 161
  version: 1
  cpuTable: .1.3.6.1.2.1.25.3.3.1.2
  usedMemory: .1.3.6.1.2.1.25.2.3.1.6
  totalMemory: .1.3.6.1.2.1.25.2.3.1.5